### ISSUE TITLE
This file does not exist in the project

### ISSUE THREAD

**Issue by TF03** [ImangazalievM/Notelin#2]
https://github.com/ImangazalievM/Notelin/blob/9eea4d499727b45049baf1d516c0597f388e45bf/app/src/main/kotlin/com/imangazaliev/notelin/NotelinApplication.kt#L7

**Comment by ImangazalievM** [comment]
```DaggerAppComponent ``` is generated class. It will be created when you build the project.

**Comment by TF03** [comment]
Oh, thanks =) I am sorry for the question, I'm just learning the Kotlin and Android =)
